#include<iostream>
using namespace std;

/*
ANALYZE
=======================
1. PROBLEM: GET THE AMOUNT OF ORANGES RECEIVE BY OWNER AND WORKERS
2. OUTPUT: DISPLAY AMOUNT OF ORANGES, THE BALANCE OF ORANGES, TOTAL AMOUNT OF ORANGES FOR WORKERS 
3. INPUT: AMOUNT THE ORANGES
4. PROCESS: CALCULATE THE AMOUNT OF ORANGES RECEIVE BY OWNER AND WORKERS
=======================
PSEUDOCODE
=======================
1. BEGIN
2. GET THE AMOUNT OF ORANGE
3. CALCULATE THE AMOUNT OF ORANGES RECEIVE BY OWNER AND WORKERS
4. DISPLAY THE TOTAL AMOUNT OF ORANGES,TOTAL AMOUNT OF ORANGES FOR OWNER, THE BALANCE, THE TOTAL AMOUNT OF ORANGES FOR WORKERS
*/

int main(){

}